### PR TITLE
Fix typo in French translations

### PR DESCRIPTION
**Pull request by NathanBnm**
I apologize for this pull request, but I just noticed there was a misspelted word 👎

### CODE REVIEW

**Comment by PlugaruT** [comment]
No worries, I'll do a quick release now :) Thanks.

**Comment by NathanBnm** [comment]
@PlugaruT okay :) Can you please check this #17 ?

**Comment by PlugaruT** [comment]
I am aware of that but right now I can't do much because translating an app is handled by the OS while the app description from AppCenter is handled by the AppCenter and right now it only supports one language.
All I can do it so mention in what languages the app is translated.

**Comment by NathanBnm** [comment]
I understand, but how others developers do ? As far as I know they can do that. I already translated other apps and they worked. I don't really understand where is the problem :)

**Comment by PlugaruT** [comment]
I'll have a look into some apps. Maybe I am wrong :)

**Comment by PlugaruT** [comment]
@NathanBnm, it's done. Translations from appdata are in the .po files.

**Pull request merged**
