### PR TITLE
Flatpak elementary

### PR DESCRIPTION
**Pull request by krisives**
This adds a Flatpak manifest so that the app is compatible with Elementary OS 6.0 and the AppCenter.

### CODE REVIEW

**Comment by PlugaruT** [comment]
@krisives Thanks for that. 
Since I no longer use eOS, can you please confirm that the app works as expected? I don't want to ship a non-working app :)

**Comment by krisives** [comment]
Yeah it worked I tested it.

**Comment by PlugaruT** [comment]
Will merge then. Thanks a lot!

**Comment by krisives** [comment]
It looks like you'll also have to make a PR to the Elementary guys so they can do the app review: https://github.com/elementary/appcenter-reviews/pulls

**Pull request merged**
