### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon didn't comply by [eOS HIG](https://elementary.io/docs/human-interface-guidelines#shadows) regarding the implementation of a pictogram. It should either be extruded or inset. The previous one was just a flat shape. I have also improved the outline that creates the highlight to make it more robust.

### CODE REVIEW

**Comment by PlugaruT** [comment]
Why does the 128px icon have a black line in the top left corner?
Also, the border of the icons is not consistent. Some icons have a border of different color. 
And also, can you keep the original color if the `';--`?

**Comment by Fatih20** [comment]
Fixed the border issue.

**Comment by Fatih20** [comment]
> And also, can you keep the original color if the `';--`? 

But why? Inset effect works best when the shape has a subtle gradient with the lighter color facing the shadow. So, I don't understand why you would want it white. The current one has a color that is already pretty light compared to the base shape so it shouldn't be hard to distinguish between the `':--` and the base shape.

**Comment by PlugaruT** [comment]
Let's see how it goes. Thanks for your contribution.

**Comment by Fatih20** [comment]
You're welcome.

**Comment by Fatih20** [comment]
Please credit me in the release note/

**Pull request merged**
